version: '3.4'

services:
  sds_webapp:
    image: webapp
    build: ./web/
    environment:
      NODE_ENV: production
    env_file:
            - 'configs.env'
    ports:
            - "3000:3000"              
  sds_sensor:
    image: sds011
    build: ./sensor/ 
    env_file:
            - 'configs.env'
    devices:
      - "/dev/ttyUSB0:/dev/ttyUSB0"
