version: '3.4'

services:
  sds_webapp:
    image: webapp
    restart: always
    deploy:
    build: 
        context: ./web
        dockerfile: Dockerfile #Dockerfile-x86 
    environment:
      TZ: "Asia/Dubai"
      NODE_ENV: production
    env_file:
            - 'configs.env'
    ports:
            - "3000:3000"              
  sds_sensor:
    image: sds011
    build: ./sensor/
    restart: always
    deploy:
    environment:
      TZ: "Asia/Dubai"
    env_file:
            - 'configs.env'
    devices:
     - "/dev/ttyUSB0:/dev/ttyUSB0"
